### ISSUE TITLE
Thoughts on using gpgme?

### ISSUE THREAD

**Issue by apeiron** [drudge/node-gpg#12]
As a strictly optional approach if it's available, have you given any thoughts to using the gpgme library instead of running the gpg program directly? gpgme is, according to the gpg developers, the [suggested way of using gpg](https://www.gnupg.org/related_software/gpgme/) from other programs.

**Comment by drudge** [comment]
This module is focused on running gpg using the cli application. If you want to use gpgme, check out https://www.npmjs.com/package/gpgme.
