### ISSUE TITLE
broken examples

### ISSUE THREAD

**Issue by tunathoni** [drudge/node-gpg#17]
Can you help me ? when i run index.js on test/ folder, error result shown : 

/Users/toni/Documents/mgg/learn/other/node-gpg/test/index.js:10
describe('gpg', function(){
^

ReferenceError: describe is not defined
    at Object.<anonymous> (/Users/toni/Documents/mgg/learn/other/node-gpg/test/index.js:10:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

**Comment by freewil** [comment]
You have to run the tests using mocha. `npm install && npm test`

**Comment by tunathoni** [comment]
Thanks @freewil for your reply, i only want to implement one of several functions, such as encrypt() function, i just try on examples/ folder, when i run node encrypt.js it shown : 


{ [Error: spawn gpg ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn gpg',
  path: 'gpg',
  spawnargs: [ '--batch', '--encrypt' ] }

i'm so confuse, can you help me? thanks for your help.

**Comment by freewil** [comment]
@tunathoni You will get that error if you don't have the `gpg` program installed and accessible from your `PATH`. You should be able to run `gpg` from the cli. 

If the file was encrypted successfully, you will get this output:

```
$ which gpg
/usr/local/bin/gpg
$ node examples/encrypt.js 
null
```

**Comment by tunathoni** [comment]
Thank you it works, but it should be xcode last updated.. Thanks for your advice...

**Comment by freewil** [comment]
gpg is also available through [homebrew](http://brew.sh/) on Mac.
