### ISSUE TITLE
Empty file created using encryption with public key

### ISSUE THREAD

**Issue by sgarciafer** [drudge/node-gpg#21]
I'm trying to programmatically encrypt a file with a public key (previously imported using the command line gnu gpg and called name@domain.com). 
The code works but the destination file is simply empty, 0 bytes of data.
Doing it using CLI bash it works, but not with the GPG node.js
How can I debug this? Any clue of why this doesn't work?

Node: v7.4.0
Express: 4.14.0

```
gpg.callStreaming(
      './uploads/tmp/'+req.files[0].filename, 
      './uploads/enc1/'+req.files[0].filename, 
      ['--recipient name@domain.com  --encrypt'],
      function(err){
                if (err) {
                    console.error('There was an error reading the file!', err);
                    return;
                }
       }
);
```

**Comment by Champii** [comment]
Can you try with an `=` between `recipient` and `name@domain.com` and with 2 separate arguments ?

```javascript
['--recipient=name@domain.com', '--encrypt']
```

**Comment by freewil** [comment]
Closing this, please re-open with a fully working example if this is still an issue.
