### ISSUE TITLE
Fail silently with streams when bad key is passed

### ISSUE THREAD

**Issue by Champii** [drudge/node-gpg#22]
I do the following : 

```javascript
// 'in' and 'out' are streams
// 'params' contains a bad key name
gpg.callStreaming(in, out, params, (err) => {
  // Here 'err' is undefined but an error should show up
})
```

The resulting stream is empty and never start to process, therefore no content is produced.

I believe this is reproducible with any `gpg` internal errors, as the only errors reported here are thoses in relation with process spawning.

I'm working right know on a fix, i'll open a PR when I will get satisfying results.

Cheers

**Comment by freewil** [comment]
Did you find out anything? If this is still a problem, then please re-open, but we need a full working example to be of any help.
