### ISSUE TITLE
Response is undefined

### ISSUE THREAD

**Issue by tnkannan** [drudge/node-gpg#32]
Hello,

The response is undefined.

code:
//
var gpg = require('gpg');
var s = 'gpg_uploads/sample.txt';
var d = 'gpg_uploads/sample.gpg';
gpg.encryptToFile({ source: s, dest: d }, function(err, data) {
    if (err) {
        console.log("Error: ", err);
    } else {
        console.log("Response: ", data);
    }
});
//

Thanks,
Kannan TN

**Comment by drudge** [comment]
`encryptToFile` doesn't return data, only a possible error
