### ISSUE TITLE
node-gpg + aws lambda

### ISSUE THREAD

**Issue by its-tayo** [drudge/node-gpg#40]
Hi guys, how do I use this lib in a lambda function, please? I see a requirement saying **"In order to use Node-GPG, you'll need to have the gpg binary in your $PATH."** 

On my local machine, I was able to get this sorted by running **brew install gpg** but have no idea of how to install gpg in a lambda function.

**Comment by steppefox** [comment]
You basically can't. Lambdas are limited in terms of installing anything except node packages. Try to look into https://github.com/openpgpjs/openpgpjs

**Comment by drudge** [comment]
https://docs.aws.amazon.com/lambda/latest/dg/images-create.html
